### PR TITLE
Omnibus prelaunch for audit

### PR DESCRIPTION
**Pull request by faddat**
An issue I've had with audits from a certain commit, is that they can miss things that change after that commit.  

If #158 is merged to main, and this is merged to the audit fixes branch, auditors will be able to see the full state of the proposed code to ship.

### CODE REVIEW

**Comment by albertandrejev** [comment]
@faddat we are not using `neutron-org:neutron_audit_informal_17_01_2023_fixes` branch, please use `neutron-org:neutron_audit_informal_17_01_2023` instead.

**Comment by albertandrejev** [comment]
Please use `main` branch instead of `neutron_audit_informal_17_01_2023_fixes` because we are not using it anymore.

**Comment by faddat** [comment]
ok :)

**Comment by zavgorodnii** [comment]
Hey! Thank you very much for your contribution. You have highlighted a lot of issues, which helped us tremendously. We addressed most of the issues in separate PRs that are already merged; some things are yet to be implemented (e.g., cosmos-specific code analysis).

We are closing this omnibus PR because it's a bit outdated now. Many thanks!

**Pull request closed without merging**
