### PR TITLE
FIX: remove incorrect dex query

### PR DESCRIPTION
**Pull request by jcompagni10**
remove `/neutron.dex.Query/UserLimitOrdersAll` as it does not exist

### CODE REVIEW

**Review by pr0n00gler — DISMISSED** [review]

**Review by sotnikov-s — DISMISSED** [review]

**Comment by sotnikov-s** [comment]
update/sdk-47 has already been merged, so I redirected the PR

**Review by sotnikov-s — APPROVED** [review]

**Review by sotnikov-s — CHANGES_REQUESTED** [review]
actually, no approve, yet: there's still inconsistency between the correct rpc and req/resp messages: LimitOrderTrancheUserAllByAddress. but still Query**AllUserLimitOrders**Request and Query**AllUserLimitOrders**Response

https://github.com/neutron-org/neutron/blob/e605ed3db4381994ee8185ba4a0ff0877d34e67f/proto/neutron/dex/query.proto#L45

**Comment by jcompagni10** [comment]
> actually, no approve, yet: there's still inconsistency between the correct rpc and req/resp messages: LimitOrderTrancheUserAllByAddress. but still Query**AllUserLimitOrders**Request and Query**AllUserLimitOrders**Response

@sotnikov-s Just to clarify are you seeing an actual problem here or just saying that for clarity the RPC name should match the request and response names?

**Comment by pr0n00gler** [comment]
@jcompagni10 please resolve conflicts here

**Comment by jcompagni10** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/7631732111

**Review by sotnikov-s — APPROVED** [review]

**Review by pr0n00gler — APPROVED** [review]

**Pull request merged**
