### PR TITLE
chore: update hermes #ntrn-1

### PR DESCRIPTION
**Pull request by NeverHappened**
updates hermes config to be used with hermes 1.6.0

parts of task:
- I've updated doc [here](https://github.com/neutron-org/neutron-docs/pull/100/files#diff-fd79bbac518078044c299cb5d809f8909bde03962a0a99b49895f5d669fdab09) as a part of update docs task
- https://github.com/neutron-org/neutron-sdk/pull/104

### CODE REVIEW

**Comment by NeverHappened** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/5610744374

**Review by foxpy — CHANGES_REQUESTED** [review]
1. [x] please add cross-links between each PR so it is easy to find them together (and also easier to merge them together later);
2. [x] take a look at [this document](https://github.com/neutron-org/neutron-docs/blob/main/docs/neutron/build-and-run/localnet.md). it suggests to install old hermes, you'll have to update it;
3. [x] this [example](https://github.com/neutron-org/neutron-sdk/tree/main/scripts/test_icq_wasm_juno_testnet) relies on old hermes version and has outdated config.toml, it has to be updated, too.

**Review by foxpy — CHANGES_REQUESTED** [review]
Thank you for your fixes, I have acknowledged them! There is one more thing, running `make init && make start-rly` prints out this warning:

```
2023-08-01T10:53:47.344307Z  WARN ThreadId(35) health_check{chain=test-1}: Chain 'test-1' has no minimum gas price value configured for denomination 'untrn'. This is usually a sign of misconfiguration, please check your chain and relayer configurations
```

The same for test-2 chain. This probably has to be fixed?

**Comment by foxpy** [comment]
Actually, this issue should be reflected in config.toml in one of neutron-sdk's examples, too :thinking:

**Comment by NeverHappened** [comment]
Okay, so this config is in the chain itself, not hermes config. More strange is that we have this setting written in app.toml on init

**Comment by foxpy** [comment]
> More strange is that we have this setting written in app.toml on init

:thinking: wow that's very interesting

I am approving this PR anyway, nice job!

**Review by foxpy — DISMISSED** [review]

**Review by pr0n00gler — APPROVED** [review]

**Review by foxpy — APPROVED** [review]

**Comment by NeverHappened** [comment]
test run : https://github.com/neutron-org/neutron-tests/actions/runs/5762605641

**Pull request merged**
