### PR TITLE
remove starport stubs

### PR DESCRIPTION
**Pull request by faddat**
- remove starport stubs from Neutron
- format code

### CODE REVIEW

**Comment by faddat** [comment]
This is mainly a cosmetic PR, and can safely be reviewed and merged post launch.

**Review by foxpy — CHANGES_REQUESTED** [review]
Honestly this sounds pretty dangerous to merge for me. Are we 100% sure in future we are not going to use any of the tools which might depend on these commented lines?

**Comment by faddat** [comment]
I would really hope that we don't.  Super bigly ser.

**Comment by quasisamurai** [comment]
It looks like this PR completely breaks `ignite`
Снимок экрана 2023-05-24 в 11 31 07

**Comment by faddat** [comment]
it totally should break ignite. 

That's the point....

**Pull request closed without merging**
