### PR TITLE
ensure LO tranches of different types are not commingled

### PR DESCRIPTION
**Pull request by jcompagni10**
Fix a bug where good-til-canceled limitOrders can be combined into the same tranche as good-til-time limitOrders under certain circumstances. This creates an undesirable behavior where good-til-canceled LOs will be purged at an arbitrary time. 

This fix ensures that GTC limit orders are never combined with GTT limit orders

### CODE REVIEW

**Comment by jcompagni10** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/8994386504

**Comment by jcompagni10** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/9025904572

**Review by NicholasDotSol — APPROVED** [review]

**Comment by jcompagni10** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/9086224661

**Review by NeverHappened — APPROVED** [review]

**Comment by jcompagni10** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/9217881998

**Pull request merged**
