### PR TITLE
chore: remove unused dex param MaxTrueTakerSpread

### PR DESCRIPTION
**Pull request by jcompagni10**
remove unused MaxTakerSpread param

neutron-sdk changes: https://github.com/neutron-org/neutron-sdk/pull/145

### CODE REVIEW

**Comment by jcompagni10** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/9323426270

**Comment by jcompagni10** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/9345042854

**Comment by pr0n00gler** [comment]
Please attach all the related PRs in other repos (neutron-sdk, neutron-dev-contracts, etc)

**Review by sotnikov-s — APPROVED** [review]

**Comment by jcompagni10** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/9373716804

**Comment by jcompagni10** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/9373716804

**Review by NicholasDotSol — APPROVED** [review]

**Review by sotnikov-s — APPROVED** [review]

**Pull request merged**
