### PR TITLE
Update main 2 #ntrn-566

### PR DESCRIPTION
**Pull request by NeverHappened**
https://github.com/neutron-org/neutron/pull/281

### CODE REVIEW

**Comment by NeverHappened** [comment]
Test run: https://github.com/neutron-org/neutron-tests/actions/runs/5463088120
check if passed!

**Comment by NeverHappened** [comment]
Updated test run https://github.com/neutron-org/neutron-tests/actions/runs/5544788968
Check if passed!

**Comment by NeverHappened** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/5545524619

**Comment by NeverHappened** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/5690226395/job/15423230879

**Review by pr0n00gler — APPROVED** [review]

**Review by swelf19 — APPROVED** [review]

**Review by albertandrejev — APPROVED** [review]

**Review by foxpy — APPROVED** [review]

**Pull request merged**
