### PR TITLE
fix: pool_metadata proto capitalization

### PR DESCRIPTION
**Pull request by jcompagni10**
Related PRs:
* https://github.com/neutron-org/neutron-integration-tests/pull/288
* https://github.com/neutron-org/neutron-dev-contracts/pull/45
* https://github.com/neutron-org/neutron-sdk/pull/139
* https://github.com/neutron-org/neutronjsplus/pull/32

### CODE REVIEW

**Review by pr0n00gler — DISMISSED** [review]

**Comment by jcompagni10** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/7631859355

**Comment by swelf19** [comment]
> https://github.com/neutron-org/neutron-tests/actions/runs/7631859355

tests failed `Response: {"code":2,"message":"codespace wasm code 9: query wasm contract failed: Error parsing into type neutron_sdk::stargate::dex::types::GetPoolMetadataResponse: missing field `Pool_metadata`","details":[]}`
you need 
1) regenerate https://github.com/neutron-org/neutron-sdk/tree/main/packages/neutron-sdk/src/proto_types, ask @sotnikov-s
2) update neutron-dev-contracts with new neutron-sdk https://github.com/neutron-org/neutron-dev-contracts/blob/main/Cargo.toml#L16

**Comment by pr0n00gler** [comment]
This PR is API breaking and will be merged in the next breaking changes release

**Comment by NeverHappened** [comment]
has conflicts

**Comment by pr0n00gler** [comment]
@jcompagni10 please fix conflicts here

**Review by swelf19 — APPROVED** [review]

**Comment by pr0n00gler** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/8850785311

**Pull request merged**
