### PR TITLE
update wasmd to v0.43 #NTRN-112

### PR DESCRIPTION
**Pull request by swelf19**
related prs: 
https://github.com/neutron-org/neutron-integration-tests/pull/213
https://github.com/neutron-org/wasmd/pull/117

### CODE REVIEW

**Comment by swelf19** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/6705200013

**Comment by swelf19** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/6706221751

**Comment by swelf19** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/6708237836

**Comment by pr0n00gler** [comment]
I think we should enable `cosmwasm_1_4` in `supportedFeatures`?

**Review by pr0n00gler — APPROVED** [review]

**Pull request merged**
