### PR TITLE
fix: change `filled_limit_order_tranche` query to `inactive_limit_order_tranche`

### PR DESCRIPTION
**Pull request by jcompagni10**
Fix query url to be consistent with struct name

### CODE REVIEW

**Comment by jcompagni10** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/7631924874

**Comment by pr0n00gler** [comment]
This PR is API breaking and will be merged in the next breaking changes release

**Comment by NeverHappened** [comment]
conflicts. is it ready? since it's in draft

**Comment by pr0n00gler** [comment]
@jcompagni10 please fix conflicts here

**Pull request merged**
