### PR TITLE
feat: set slinky state in upgrade handler

### PR DESCRIPTION
**Pull request by aljo242**
Set the `x/oracle` and `x/marketmap` state from our core market config
- add corresponding tests

NOTE: this PR is on top of https://github.com/neutron-org/neutron/pull/516

### CODE REVIEW

**Review by NeverHappened — CHANGES_REQUESTED** [review]
looks good! What do we need to merge this:
- init-neutrond.sh should set market_authorities instead of market_authority for local running and testing.
- resolve conflicts

**Review by NeverHappened — APPROVED** [review]

**Review by pr0n00gler — APPROVED** [review]

**Comment by pr0n00gler** [comment]
Could you embed this file via `//go:embed static` directive?
it's really not convenient to share an additional file with validators

**Comment by NeverHappened** [comment]
please run gofumpt

**Comment by NeverHappened** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/9108303003 (ran on our same branch (in neutron repo) linted)

**Pull request merged**
